version: "3"
services:
  postgres:
    container_name: postgres_task_tracker
    image: postgres:latest
    ports:
      - "6432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env